name: myapp

    
  
services: 
  postgres:
    image: 'postgres:latest'
    attach: true


  redis:
    image: 'redis:latest'
    depends_on:
      - postgres


  nginx:
    container_name: nginx
    annotations:
      com.example.nginx: nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'


  api:
    container_name: api
    blkio_config:
      weight: 600
      weight_device:
        - path: /app
    cap_add:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_completed_successfully
        required: true
        restart: true  
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    
        
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432


  client:
    container_name: clientside
    build:
      dockerfile: Dockerfile.dev
      context: ./client
      
    volumes:
      - /app/node_modules
      - ./client:/app


  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    volumes_from:
      - api:ro

